name: Build storybook
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install project dependencies
        run: yarn install --pure-lockfile
      - name: Update gh-pages
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          rm -rf storybook/
          yarn build:storybook
          touch storybook/.nojekyll
          yarn publish:storybook -m 'chore: build storybook' -t
