name: Publish
on:
  push:
    branches: [ main ]

jobs:
  publish:
    if: contains(github.event.head_commit.message, 'chore(release)') == false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install project dependencies
        run: yarn install --pure-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: setup git config
        run: |
          git config --global user.name "standardci"
          git config --global user.email "ci@standardnotes.com"
      - name: Bump version
        run: yarn release
      - name: Push to GitHub
        run: git push --follow-tags origin main
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
